// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3QAIVykpcneNoZEu-zRtvcvfPIZ9V8WQ',
    appId: '1:397421713608:web:b91d4aee06dc7a938a6dfd',
    messagingSenderId: '397421713608',
    projectId: 'latterpracj',
    authDomain: 'latterpracj.firebaseapp.com',
    storageBucket: 'latterpracj.appspot.com',
    measurementId: 'G-NCKVTZRENP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaeLwKwoAwaOtHJcRlre6B7ydjG69CvY8',
    appId: '1:397421713608:android:0a54b4a8b01adc6e8a6dfd',
    messagingSenderId: '397421713608',
    projectId: 'latterpracj',
    storageBucket: 'latterpracj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgPhyiWfool0QgLuso57cuyqesFgC7WY',
    appId: '1:397421713608:ios:73bf795c8c402f4a8a6dfd',
    messagingSenderId: '397421713608',
    projectId: 'latterpracj',
    storageBucket: 'latterpracj.appspot.com',
    iosClientId: '397421713608-imu5bogutdbqhnps57ubv4597ncmhbet.apps.googleusercontent.com',
    iosBundleId: 'com.example.latterPracj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgPhyiWfool0QgLuso57cuyqesFgC7WY',
    appId: '1:397421713608:ios:cbb419510542f6ed8a6dfd',
    messagingSenderId: '397421713608',
    projectId: 'latterpracj',
    storageBucket: 'latterpracj.appspot.com',
    iosClientId: '397421713608-sa4meq5tqteuqs858ejpsne7h3iev1ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.latterPracj.RunnerTests',
  );
}
